import { Montserrat } from 'next/font/google'

import Container from '@layout/Container'
import Navbar from '@layout/Navbar'
import Footer from "@layout/Footer";

import "./globals.css";

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: "Bluco",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navbar />
        </header>
        <main className={montserrat.className}>
          <Container customClass="min-height">
            {children}
          </Container>
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
